### PR TITLE
Refactor field initializations in reference classes

### PR DESCRIPTION
**Pull request by Rochet2**
This pull request refactors the reference class field initialization. It also adds linux temp files to gitignore.
The purpose is to simplify the Reference class and it's subclasses.

The Reference class and the subclasses had exact same name variables that were meant for the same thing, so I simply removed everything from subclasses. I removed unneeded helper functions and due to the changes the subclasses no longer need to implement their own "get" functions for fields.
Also now instead of required and existing fields there are required and optional fields that, when combined, create the set of existing fields.

As a result implementing and testing new reference subclasses should be easier. Also cobertura reports now 100% pass on all reference classes.

### CODE REVIEW

**Comment by Salmela** [comment]
Hi
The reason why the reference sub classes had the static sets, was so that the code won't create new instances of exactly same sets for each Reference. And as far as I know the code of this patch creates these new instances.

The problem isn't just about wasting main memory. Our code uses object streams, which serializes all References into a save file. So when the application writes out the references, then for each reference there would be two sets of fields.  Now when we reuse those field sets then, the ObjectOutputStream is clever enough to only write an instance once to the file. We could even get rid of all set instance in the file by making the sets purely static and never even giving its reference to Reference instances. But we had no time to do so and it wasn't high priority.

Implementation of EnumSet.of method 
grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/util/EnumSet.java#EnumSet.of(java.lang.Enum)

ObjectOutputStream uses HandleTable, which maps object instances to id values, which are used when instance is referenced more than once.
http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/io/ObjectOutputStream.java#ObjectOutputStream.HandleTable

Thank you for your time

**Comment by Salmela** [comment]
If you have motivation to still work on this. You could just remove the field set variables from Reference abstract class. So that Reference instances won't have reference to field sets.

To remove last commit you can do the following
`git reset --hard HEAD~`
After that you have to use force flag when you push.
`git push origin master --force`

You should never do these commands at public repo, but it's not problem here because the branch is your private feature branch.

**Comment by Rochet2** [comment]
Hmm, maybe should have gone for a smaller refactor.
Nevertheless I made this new change that refactors fields to a separate class entirely.
This way they will not be in Reference class in any way and will not be saved to disk at all and only one instance of them exists in memory at all times.

If you feel like this is too intrusive or not the way you want to go, then do close the PR.

**Comment by Redande** [comment]
Sorry,
Our demo starts soon, and we have no time to go through and merge your pull request.
Thanks for the effort!

**Pull request closed without merging**
